#!/bin/bash -
#
# fl - fastlane wrapper
#
# usage:
#       fl [app] args...
#
#       if APP is the name of an app subproject, fl will 'cd' to
#       ${app}_app before executing 'fastlane args...'

# Setting JAVA_HOME is another way to make gradlew work, but for now use tools/jdkrun.sh
#export JAVA_HOME=/c/Program\ Files/Android/Android\ Studio/jbr

export FASTLANE_SKIP_ACTION_SUMMARY=1

# If $1 is the name of an app, shift it off and cd to subdir
if [ $# -gt 0 ]; then
    app="$1"
    if [ -d "${app}_app" ]; then
        cd "${app}_app"
        shift
    fi
fi

# 'bundle exec' is only slightly faster, but it does eliminate a warning
exec bundle exec fastlane "$@"
#exec fastlane "$@"
